### ISSUE TITLE
Requests to the API do not return data

### ISSUE THREAD

**Issue by runobe** [TBFY/knowledge-graph-API#37]
Hi, These requests to the API do not return data:
http://tbfy.librairy.linkeddata.es/kg-api/contract
http://tbfy.librairy.linkeddata.es/kg-api/contracting-process
http://tbfy.librairy.linkeddata.es/kg-api/award
These requests return data:
http://tbfy.librairy.linkeddata.es/kg-api/organisation
http://tbfy.librairy.linkeddata.es/kg-api/tender/

**Comment by fyedro** [comment]
Due to the new release of the KG, the namespace and URIs of the resources have changed.  We are working on it, we will try to make it available again as soon as possible.

**Comment by fyedro** [comment]
solved:
http://tbfy.librairy.linkeddata.es/kg-api/contract
http://tbfy.librairy.linkeddata.es/kg-api/contracting-process
http://tbfy.librairy.linkeddata.es/kg-api/award
these three resources should be working now (note that contracting-process has been renamed to contractingProcess)

this issue is still in progress
